### ISSUE TITLE
Regarding the future of this package

### ISSUE THREAD

**Issue by luizberti** [brazilian-utils/old-python#10]
Hey @camilamaia! I noticed that you've been cleaning up this project recently, so I have a proposal to make:

## Historical Context
I am the owner of [the `brutils` package in PyPI](https://github.com/luizberti/brutils), which predates the `brazilian-utils` package and organization by about roughly 2 years if I recall correctly.

My project (unlike most in the Python ecosystem, including this one), is thoroughly documented both in Portuguese and English, is thoroughly tested and fully supports both python 2.7 and 3.x _(2.7 is still important for legacy applications)_, exposes an ergonomic and type-hinted API with additional utility functions, and doesn't suffer from extensive code quality issues like some others do (even on this one, `validate_first_digit` and `validate_second_digit` are a clear smell of code duplication, as they are almost identical and implement the same checksumming algorithm, but in different positions in the array).

Mine also has the benefit that it already implements CNPJ which this one doesn't, and its internal architecture was made to favor extending the package with support for other types of documents by simply adding more internal modules. Also, like this one, it has zero dependencies outside of Python itself (although the tests can be ran with `pytest` as well if preferred).

When this organization started a few years ago, I offered to transfer my package so that it would be maintained under it, but that conversation died out and nothing was done.

## The Proposal
Given the renewed interest in this package from you, what would you say to us instead of trying to refactor this package into a better shape, transfer mine to the organization (both here and in PyPI) making it the official one, and deprecating this one?

It would lessen the maintenance burden for everyone, and de-fragment the ecosystem (especially since my crate is very old and shares a very similar name)

What do you say? :smiley: 

Regards, Luiz.

**Comment by luizberti** [comment]
Also tagging @alexrochas and @guilhermecomum 

PS: It seems I have been removed from the organization, probably due to inactivity hehe. If we decide to go through with this, I'd probably need to be added again to transfer my repository, but we can settle that later :)

**Comment by camilamaia** [comment]
Hi @luizberti, thanks for the proposal! I've just joinned this project, so I am totally in with whatever @alexrochas and @guilhermecomum decided.

But if you'd like to hear my opinion, these are my 2 cents: 

- I like the idea of putting together the efforts and having only one project. This way, we we'd have more people to maintain, more people to develop new features, and one better solution. That was the reason I started to looking for existent solutions instead of creating a new one;
- Both projects don't have much code yet. `brutils` indeed have one more feature - the cnpj one - comparing with this project. But they are quite in initial state if you compare with the brazilian-utils js version. So it is totally fine for me to use either repos. Migrating brutils to here or the other way around. 
- As @luizberti suggested, I like the idea of having it below this org, since it is quite popular already

**Comment by camilamaia** [comment]
ps: I will keep creating the issues here, just because I'm on fire hahaha But I can migrate them later if needed, no problem

**Comment by camilamaia** [comment]
Since @hyanmandian said yes, let's do it?

Here is my suggestions of how to do it:

1. @camilamaia: Add @luizberti to the `brazilian-utils` org. (which role should I give to him @hyanmandian?)
2. @luizberti: Move `brutils` to `brazilian-utils` org; 
3. @camilamaia: rename it from `brutils` to `brutils-python`;
4. @camilamaia: move issues from this repo to the new one;
5. @camilamaia: alert that this repo is deprecated in the readme and link to the new one;
6. later on, in the future: achieve this repo if needed, to avoid confusion.

How does that sound? Does it make sense?

**Comment by luizberti** [comment]
@camilamaia sounds good! :)

As soon as I get added back to the org I'll transfer :+1:

**Comment by guilhermecomum** [comment]
Hey @camilamaia and @luizberti, first of all congrats for this awesome works! I'm ok with any decisions you decide to keep this proejct alive!

**Comment by camilamaia** [comment]
@hyanmandian I've just noticed that I am not in the org either. Would you mind adding @luizberti to the org, please?

**Comment by hyanmandian** [comment]
Done @camilamaia I gave you owner role in our organization. Thank you for work to keep this library alive 😄

**Comment by camilamaia** [comment]
Thank you very much @hyanmandian ! @luizberti I sent an invite to you to join the org.

**Comment by camilamaia** [comment]
hey, @luizberti did you have a chance to try to move the repo to this org? Let me know if you need any help!

**Comment by luizberti** [comment]
oops sorry, I forgot! migrating it now ...

**Comment by luizberti** [comment]
@camilamaia done! https://github.com/brazilian-utils/brutils

you might want to change the repo name to `brutils-python`, given that I don't have access to do that :)

**Comment by camilamaia** [comment]
Awesome, thanks @luizberti! 

1. ✅ @camilamaia: Add @luizberti to the `brazilian-utils` org. (which role should I give to him @hyanmandian?)
2. ✅ @luizberti: Move `brutils` to `brazilian-utils` org; 
3. ✅ @camilamaia: rename it from `brutils` to `brutils-python`;
4. ✅ @camilamaia: move issues from this repo to the new one;
5. ✅ @camilamaia: alert that this repo is deprecated in the readme and link to the new one;
6. later on, in the future: achieve this repo if needed, to avoid confusion.

I am closing this issue, since only the step 6 is missing now, and it takes time.

Also, this is the PR for the step 5: https://github.com/brazilian-utils/python/pull/19, if you have some time to review it, i'd appreciate it.

Thank you all for the team work!
